# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FirebaseExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseExample
	pod 'PinLayout'
	pod 'Kingfisher'
	pod 'Firebase/Analytics'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'
end
